/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "split.h"

bool_t
xdr_compte (XDR *xdrs, compte *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nom, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->prenom, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->email, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->pays, 50))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->solde))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_abonnement (XDR *xdrs, abonnement *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nom, 50))
		 return FALSE;
	 if (!xdr_compte (xdrs, &objp->comptes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max_compte))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_modif_solde (XDR *xdrs, modif_solde *objp)
{
	register int32_t *buf;

	 if (!xdr_compte (xdrs, &objp->compte))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->solde))
		 return FALSE;
	return TRUE;
}
