/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SPLIT_H_RPCGEN
#define _SPLIT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct compte {
	char *nom;
	char *prenom;
	char *email;
	char *pays;
	int solde;
};
typedef struct compte compte;

struct abonnement {
	char *nom;
	compte comptes;
	int prix;
	int max_compte;
};
typedef struct abonnement abonnement;

struct modif_solde {
	compte compte;
	int solde;
};
typedef struct modif_solde modif_solde;

#define ABONNEMENT_PROG 0x31240000
#define ABONNEMENT_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_ABONNEMENT 1
extern  abonnement * get_abonnement_1(char **, CLIENT *);
extern  abonnement * get_abonnement_1_svc(char **, struct svc_req *);
#define ADD_COMPTE 2
extern  void * add_compte_1(compte *, CLIENT *);
extern  void * add_compte_1_svc(compte *, struct svc_req *);
#define GET_COMPTE 3
extern  compte * get_compte_1(char **, CLIENT *);
extern  compte * get_compte_1_svc(char **, struct svc_req *);
#define ADD_ABONNEMENT 4
extern  void * add_abonnement_1(abonnement *, CLIENT *);
extern  void * add_abonnement_1_svc(abonnement *, struct svc_req *);
#define suppr_compte 5
extern  void * suppr_compte_1(compte *, CLIENT *);
extern  void * suppr_compte_1_svc(compte *, struct svc_req *);
#define add_solde 6
extern  void * add_solde_1(modif_solde *, CLIENT *);
extern  void * add_solde_1_svc(modif_solde *, struct svc_req *);
#define moins_solde 7
extern  void * moins_solde_1(modif_solde *, CLIENT *);
extern  void * moins_solde_1_svc(modif_solde *, struct svc_req *);
extern int abonnement_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_ABONNEMENT 1
extern  abonnement * get_abonnement_1();
extern  abonnement * get_abonnement_1_svc();
#define ADD_COMPTE 2
extern  void * add_compte_1();
extern  void * add_compte_1_svc();
#define GET_COMPTE 3
extern  compte * get_compte_1();
extern  compte * get_compte_1_svc();
#define ADD_ABONNEMENT 4
extern  void * add_abonnement_1();
extern  void * add_abonnement_1_svc();
#define suppr_compte 5
extern  void * suppr_compte_1();
extern  void * suppr_compte_1_svc();
#define add_solde 6
extern  void * add_solde_1();
extern  void * add_solde_1_svc();
#define moins_solde 7
extern  void * moins_solde_1();
extern  void * moins_solde_1_svc();
extern int abonnement_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_compte (XDR *, compte*);
extern  bool_t xdr_abonnement (XDR *, abonnement*);
extern  bool_t xdr_modif_solde (XDR *, modif_solde*);

#else /* K&R C */
extern bool_t xdr_compte ();
extern bool_t xdr_abonnement ();
extern bool_t xdr_modif_solde ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SPLIT_H_RPCGEN */
