/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "split.h"
static abonnement abonnements[100];
static int nb_abonnements = 0;

static compte comptes[100];
static int nb_comptes = 0;

abonnement *
get_abonnement_1_svc(char **argp, struct svc_req *rqstp)
{
	for (int i = 0; i < nb_abonnements; i++) {
        if (strcmp(abonnements[i].nom, *argp) == 0) {
            return &abonnements[i];
        }
    }
    return NULL;
}

// Ajouter un compte
void *
add_compte_1_svc(compte *argp, struct svc_req *rqstp)
{
    if (nb_comptes < 100) {
        comptes[nb_comptes++] = *argp;
    } else {
        printf("Limite de comptes atteinte.\n");
    }
}

compte *
get_compte_1_svc(char **argp, struct svc_req *rqstp)
{
	for (int i = 0; i < nb_comptes; i++) {
        if (strcmp(comptes[i].email, *email) == 0) {
            return &comptes[i];
        }
    }
    return NULL;
}

void *
add_abonnement_1_svc(abonnement *argp, struct svc_req *rqstp)
{
	if (nb_abonnements < 100) {
        abonnements[nb_abonnements++] = *argp;
    } else {
        printf("Limite d'abonnements atteinte.\n");
    }
}

void *
add_abonner_1_svc(compte *argp, struct svc_req *rqstp)
{
	    compte *c = get_compte_1_svc(&argp->compte.email, rqstp);
    abonnement *a = get_abonnement_1_svc(&argp->abonnement.nom, rqstp);
    if (c != NULL && a != NULL) {
        if (a->comptes.comptes_len < &argp->abonnement.max_compte) {
            a->comptes.comptes_val[a->comptes.comptes_len++] = *c;
        } else {
            printf("Limite de comptes pour cet abonnement atteinte.\n");
        }
    } else {
        printf("Compte ou abonnement introuvable.\n");
    }
}




void *
suppr_compte_1_svc(compte *argp, struct svc_req *rqstp)
{
	static char * result;

	    if (strcmp(comptes[i].email, *email) == 0) {
            comptes[i]=compte_new;
        }

	return (void *) &result;
}
