/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "split.h"

bool_t
xdr_compte (XDR *xdrs, compte *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nom, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->prenom, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->email, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->pays, 50))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_abonnement (XDR *xdrs, abonnement *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nom, 50))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->comptes.comptes_val, (u_int *) &objp->comptes.comptes_len, ~0,
		sizeof (compte), (xdrproc_t) xdr_compte))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->prix.prix_val, (u_int *) &objp->prix.prix_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->max_compte.max_compte_val, (u_int *) &objp->max_compte.max_compte_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_abonnement_compte (XDR *xdrs, abonnement_compte *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->compte.compte_val, (u_int *) &objp->compte.compte_len, ~0,
		sizeof (compte), (xdrproc_t) xdr_compte))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->abonnement.abonnement_val, (u_int *) &objp->abonnement.abonnement_len, ~0,
		sizeof (abonnement), (xdrproc_t) xdr_abonnement))
		 return FALSE;
	return TRUE;
}
